### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by adocampo** [PWDSafe/PWDSafe#30]
Hello,

I've just stumbled upon this project, and it seems quite interesting, as I need a password manager integrated with AD/LDAP, and there are just a handful of open source projects in this line of working, and most of them have their development stalled.

I've tried to install it via docker with the following docker-compose

```
version: '3.3'
services:
    pwdsafe:
        container_name: pwdsafe
        ports:
            - '81:80' # I have the port 80 already taken
            - '8081:8080' # I have the port 8080 already taken
        environment:
            - 'APP_KEY=base64:Lk02IG5f78oAd/K0GCSVChtH15+0Q+5kjdd81CwV1f0='
            - DB_HOST=192.168.10.23
            - DB_PORT=3306
            - DB_DATABASE=pwdsafe
            - DB_USERNAME=pwdsafeadmin
            - DB_PASSWORD=supersecretpassword
            - LOG_CHANNEL=stderr
            - APP_DEBUG=false
            - APP_ENVIRONMENT=production
            - USE_LDAP=true
            - 'AD_SRV=ldaps://dc01.example.com'
            - AD_DOM=ad
            - 'AD_USERCONTAINER=CN=passwords,OU=Security Groups,OU=company,DC=example,DC=com'
        image: 'pwdsafe/pwdsafe:2.1.18'
```

I've created a database named pwdsafe on my mariadb server (192.168.10.23) and created a user with privileges on that database:
```
create database pwdsafe;
CREATE USER 'pwdsafeadmin'@'%' IDENTIFIED BY 'supersecretpassword';
GRANT ALL PRIVILEGES ON pwdsafe.* TO 'pwdsafeadmin'@'%';
flush privileges;
```

Then, acceding the hostip:8081 a login form appears, but I cannot login at all. It says "Wrong username or password". I've tried to simplyfy the `AD_USERCONTAINER` to something like `AD_USERCONTAINER=CN=Users,DC=example,DC=com` and create a user there called testuserpwd, but the error still persists.
Enabling APP_DEBUG shows a footer on the website, but I'm a complete strange to Laravel or php, so I don't know what this can mean
![image](https://user-images.githubusercontent.com/2266612/214178476-ca91a47e-4ad2-40d0-aad1-f2de6f2e3bc1.png)
![image](https://user-images.githubusercontent.com/2266612/214178507-0b6d032e-6e56-4b22-88c3-f9b5328a8d0f.png)

Oh, I also changed from ldaps://<domain_controller_fqdn> to ldap://<domain_controller_IP>, but the result is the same...

Any ideas?
